//users requests:


### GET All users:
GET http://localhost:8080/api/v1/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMzE1NDUwMH0.XaRGi5cil98w2anyMwjTI90u4Wq9Dk2UIDBdLBC4qCY


### Add a user:
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": {
    "first": "EDEN",
    "last": "DRORI"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "DRORI@batcave.com",
  "isBusiness": true,
  "password": "123456aA!"
}


### Login:
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "DRORI@batcave.com",
  "password": "123456aA!"
}



### GET user by id
GET http://localhost:8080/api/v1/users/6584138779c7c62b862e2017
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU0NjI0fQ.4FzMV4CUu24FOgBdVkqSnmxfqD7ObeaLEwq7d3Ax2ZY

 
### GET user by id with JWT of admin:
GET http://localhost:8080/api/v1/users/6584138779c7c6862e2017
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMzE1NDUwMH0.XaRGi5cil98w2anyMwjTI90u4Wq9Dk2UIDBdLBC4qCY

### PUT edit user:
PUT http://localhost:8080/api/v1/users/6582fd714ea23b54001a5c48
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU0NjI0fQ.4FzMV4CUu24FOgBdVkqSnmxfqD7ObeaLEwq7d3Ax2Z
Content-Type: application/json

{
  "name": {
    "first": "EDEN!",
    "last": "DRORI!"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "DRORI@batcave.com",
  "isBusiness": true,
  "password": "123456aA!" 
}

### DELETE user:
DELETE http://localhost:8080/api/v1/users/6584138779c7c62b862e2017
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU0NjI0fQ.4FzMV4CUu24FOgBdVkqSnmxfqD7ObeaLEwq7d3Ax2ZY


### PATCH user change isBizz status:
PATCH http://localhost:8080/api/v1/users/6584159a79c7c62b862e2047
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU1MTQxfQ.ZcbviGQ628tYQjZX5A30Qk_q72JV7dxvgENUZrIrT78


//cards requests:

### POST create card:
POST http://localhost:8080/api/v1/cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU1MTQxfQ.ZcbviGQ628tYQjZX5A30Qk_q72JV7dxvgENUZrIrT78
Content-Type: application/json

{
  "title": "eden drori",
  "subtitle":"3",
  "description":"hellooooooo",
  "web":"www.fsgsf.co.il",
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "eden@batcave.com"
}


### GET cards:
GET http://localhost:8080/api/v1/cards

### GET card by id:
GET http://localhost:8080/api/v1/cards/6582fd724ea23b54001a5c5c


### PUT edit cards:
PUT http://localhost:8080/api/v1/cards/6584161a79c7c62b862e205c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU1MTQxfQ.ZcbviGQ628tYQjZX5A30Qk_q72JV7dxvgENUZrIrT78
Content-Type: application/json

{
  "title": "eden !!!!!!!!!",
  "subtitle":"3",
  "description":"hellooooooo",
  "web":"www.fsgsf.co.il",
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "Way@batcave.com"
}

### GET my cards:
GET http://localhost:8080/api/v1/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU1MTQxfQ.ZcbviGQ628tYQjZX5A30Qk_q72JV7dxvgENUZrIrT78


### DELETE my cards:
DELETE http://localhost:8080/api/v1/cards/6584161a79c7c62b862e205c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRST1JJQGJhdGNhdmUuY29tIiwiaWF0IjoxNzAzMTU1MTQxfQ.ZcbviGQ628tYQjZX5A30Qk_q72JV7dxvgENUZrIrT78



### PATCH like cards
PATCH  http://localhost:8080/api/v1/cards/6582fd724ea23b54001a5c5dc
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMzE1NDUwMH0.XaRGi5cil98w2anyMwjTI90u4Wq9Dk2UIDBdLBC4qCY
Content-Type: application/json
